### ISSUE TITLE
Error: could not find or load main class ic.IronClad

### ISSUE THREAD

**Issue by jboadas** [mikera/ironclad#2]
I just download the source and do a mvn assembly:single inside the ironclad directory, everythig works ok and I got
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:06 min
[INFO] Finished at: 2016-04-04T17:16:53-04:30
[INFO] Final Memory: 10M/26M
[INFO] ------------------------------------------------------------------------

But when I want to run the game I got Error: could not find or load main class ic.IronClad, I am doing something wrong ?

**Comment by PaulSchulz** [comment]
I'm getting the same issue. What should the correct command (CLI) to use to run the 'jar'.

I've tried:
  java  -jar target/ironclad-0.0.2-SNAPSHOT-jar-with-dependencies.jar

**Comment by mikera** [comment]
On windows the following works fine for me (after doing `mvn assembly:single` in the project directory)

`java -jar target\ironclad-0.0.2-SNAPSHOT-jar-with-dependencies.jar`

On Linux/Max you probably need to change the `\` to `/` of course. Or you can just rename the `.jar` to whatever you like and put it wherever you want: It should be entirely self-contained after building will all the dependencies.

**Comment by PaulSchulz** [comment]
Hi Mikera,
Running under Linux (Ubuntu) might require some additional options (which I am unsure about), as it complains with the above error.

$ java -jar target/ironclad-0.0.2-SNAPSHOT-jar-with-dependencies.jar
Error: Could not find or load main class ic.IronClad

**Comment by PaulSchulz** [comment]
Issue looks more to be how the build happens on Linux, rather than windows.

I took my 'jar' file that was built on Ubuntu, and copied it to Windows to run.

With your command for running on Windows, I get the same error as when I ran it on Linux.
(Eg, the jar that I built on Linux has the same error on Linux and Windows.)

**Comment by mikera** [comment]
Sounds like some kind of issue with the build process on Linux then - not easy for me to debug since I only have access to Windows at the moment but I have pushed some pom.xml updates adding extra executions to the maven-assembly-plugin that might fix it. 

@PaulSchulz how big is the compiled jar with dependencies on Linux? It should be about 10-11mb I think, if substantially smaller than that then some contents are probably missing?

**Comment by PaulSchulz** [comment]
With the changes the jar size went from 5.8M  -> 6.1M (not a huge change) with the same error.

What verison of Java are you using? 
Ubuntu defaults to OpenJDK 8, so I also installed Oracle Java 8, but without any noticable difference..

**Comment by mikera** [comment]
That sounds like it is probably building the jar without all the dependencies. I'm using OpenJDK 11, Maven 3.5 but Ironclad should build OK with any Java version 7 or later.

**Comment by Folcon** [comment]
Hey, spent a bit of time digging into this =)... I can only validate this on mac, should work on linux though :)...

What you need to do is:
```
mvn package
```

This should pull all the deps and give you:
```
target/ironclad-0.0.2-SNAPSHOT-jar-with-dependencies.jar  # <-- use that one
target/ironclad-0.0.2-SNAPSHOT.jar
```

Run it now with:
```
java -jar target/ironclad-0.0.2-SNAPSHOT-jar-with-dependencies.jar
```

Voila =)...
<img width="1261" alt="Screenshot 2020-04-05 at 12 40 19" src="https://user-images.githubusercontent.com/123055/78473708-a481cd00-773a-11ea-8603-3e9958f938bc.png">

**Comment by mikera** [comment]
Glad you managed to get it working!
